### ISSUE TITLE
It isn't clear how to set linear=no when adding item to book

### ISSUE THREAD

**Issue by slonopotamus** [skoji/gepub#119]
Suppose, I have:

```ruby
book = GEPUB::Book.new
item = book.add_ordered_item 'nav.xhtml'
```

This will add `<itemref idref="nav.xhtml"/>` to `<spine>` in `package.opf`.

Now I want to set `linear="no"` attribute for this itemref. How I do that?

**Comment by skoji** [comment]
You can add `linear="no"` by doing this in current API.

``` ruby
book = GEPUB::Book.new
item = book.add_ordered_item 'nav.xhtml'
book.spine.itemref_by_id[item.id].linear = 'no'
```

Yes, I know it is not clear and not clean at all. I will consider to add more clear API for `linear` and `page-spread`.

**Comment by slonopotamus** [comment]
I ended up not using `linear="no"` because it works inconsistently across ebook readers, so there isn't much value fixing this issue.
