### ISSUE TITLE
Don't bundle the test suite

### ISSUE THREAD

**Issue by mojavelinux** [skoji/gepub#80]
The test suite is inflating the size of gem. As of the 1.0.2 release, the gem is over 10MB. There's no reason to publish the test suite with the gem since it isn't used at runtime. It's better just to keep the test suite in the git repository (available for a release via a tag).

**Comment by mojavelinux** [comment]
Thanks!

**Comment by skoji** [comment]
Thank you for the issue, I was not aware of this !
