### ISSUE TITLE
Update Nokogiri to 1.11.0 when ready 

### ISSUE THREAD

**Issue by skoji** [skoji/gepub#93]
* https://github.com/sparklemotion/nokogiri/issues/1961
* When Nokogiri 1.11.0 is released, we should remove [this](https://github.com/skoji/gepub/blob/5b9a59361b17029e5fdb164bcc109e37528678e4/.github/workflows/test.yml#L10-L13)

**Comment by chloerei** [comment]
Is it possible to replace nokogiri with rexml? Install nokogiri in ubuntu need almost 200mb for compilation tools, it's too big for a command line tool that I want to distribute via docker...

**Comment by skoji** [comment]
@chloerei I think it's possible but not so easy. I'm thinking of introducing XML abstraction layer to switch XML library, like [epub-parser](https://gitlab.com/KitaitiMakoto/epub-parser).

**Comment by chloerei** [comment]
@skoji If Nokogiri is not superior to REXML under the requirements of this gem(Maybe performance?), I think REXML is enough. Abstraction layer required extra work and maybe not important for user.

Also I found I can install ruby-nokogiri package from ubuntu repo, that need 34.8 MB space, less then compile at install time. I feel better now.

**Comment by skoji** [comment]
I think performance is important for some use cases. (e.g. asciidoctor-epub)

**Comment by chloerei** [comment]
I also depend on Nokogiri to parse HTML, so don't need to worry about it.  😂

**Comment by flavorjones** [comment]
Nokogiri release candidate [v1.11.0.rc1](https://github.com/sparklemotion/nokogiri/releases/tag/v1.11.0.rc1) has been released with precompiled native libraries for Windows and Ruby 2.7. Please give it a whirl and let me know if you have any problems.

**Comment by slonopotamus** [comment]
I can't believe there's still no stable Nokogiri release for Ruby 2.7 on Windows.

**Comment by flavorjones** [comment]
@slonopotamus please see https://github.com/sparklemotion/nokogiri/issues/2029#issuecomment-648130815

**Comment by flavorjones** [comment]
Nokogiri v1.10.10 has been released with precompiled support for Ruby 2.7 on Windows.

**Comment by slonopotamus** [comment]
I've created #120 that enables CI on Windows + Ruby 2.7 (and it passes)
