### ISSUE TITLE
cleanup_for_epub3 prevents reproducible builds

### ISSUE THREAD

**Issue by slonopotamus** [skoji/gepub#97]
Currently, it is impossible to create two byte-to-byte identical EPUB files via gepub because it unconditionally [sets modified time to current time](https://github.com/skoji/gepub/blob/v1.0.7/lib/gepub/book.rb#L428) when user calls `generate_epub_stream` or `generate_epub`.

Please, add an option to disable this behavior, so that gepub user can explicitly set modified date to a fixed timestamp. Alternative way: only update modified date in `cleanup_for_epub3` if it wasn't set explicitly.

More info about reproducible builds concept is available on https://reproducible-builds.org/

**Comment by slonopotamus** [comment]
After a bit more thinking, possibly what you did is not as good. Now, last modified will not update if you load existing epub, modify it and save back. Riight? Seems like, we actually need an option to say whether update last modified date or not.

**Comment by slonopotamus** [comment]
@skoji what do you think?

**Comment by skoji** [comment]
> Now, last modified will not update if you load existing epub, modify it and save back. Right? 

Yes, that’s right. Original behavior is intended to prevent that case. 

But the original behavior also made `book.lastmodified=` meaningless.

**Comment by skoji** [comment]
OK I'm going to change on parsed EPUB:

Update lastmodified on save even if parsed lastmodified exists, unless client explicitly sets lastmodified.
